backend:
  name: git-gateway # Link the CMS with a Git repo via Netlify
  branch: main # Branch to update (optional; defaults to master)
local_backend: true
public_folder: /img
media_folder: /src/img

collections:
  - label: "Portal one pages"
    name: "portal-one"
    folder: "src/pages/portal-one"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "portal-one-page",
        }
      - { label: Title, name: title, widget: string }
      - { label: Colour, name: colour, widget: color }
      - {
          label: Tables,
          name: table,
          widget: list,
          fields:
            [
              { label: Table Title, name: tablename, widget: string },
              {
                label: Resources,
                name: resource,
                widget: list,
                fields:
                  [
                    { label: File Name, name: filename, widget: string },
                    { label: Filetype, name: filetype, widget: string },
                    { label: File, name: file, widget: file },
                  ],
              },
            ],
        }
